# Generated by Django 3.1.3 on 2021-07-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='image',
            field=models.CharField(default='background.png', max_length=50),
        ),
    ]
