# Generated by Django 3.1.3 on 2021-08-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0003_volumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumes',
            name='volume',
            field=models.IntegerField(default=1),
        ),
    ]
