# Generated by Django 3.1.3 on 2021-08-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0004_volumes_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumes',
            name='link',
            field=models.CharField(max_length=350),
        ),
    ]
