# Generated by Django 3.1.3 on 2021-08-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0006_contents_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='type',
            field=models.CharField(choices=[('MAP', 'map'), ('IMAGE', 'image')], default='image', max_length=50),
        ),
    ]
