# Generated by Django 3.1.3 on 2021-08-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0007_contents_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='type',
            new_name='types',
        ),
    ]
