# Generated by Django 3.1.3 on 2021-08-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0008_auto_20210826_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='image',
            field=models.CharField(default='background.png', max_length=250),
        ),
    ]
