# Generated by Django 3.1.3 on 2021-10-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0009_auto_20210826_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='EIA_Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=50)),
                ('Title', models.CharField(default='Title', max_length=50)),
                ('Content', models.TextField()),
                ('types', models.CharField(choices=[('MAP', 'map'), ('IMAGE', 'image')], default='image', max_length=50)),
                ('image', models.CharField(default='background.png', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ImageReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=250)),
                ('map', models.CharField(max_length=250)),
            ],
        ),
    ]
