# Generated by Django 3.1.3 on 2021-12-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0011_auto_20211220_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumes',
            name='nts_link',
            field=models.CharField(default='link', max_length=350),
        ),
    ]
