# Generated by Django 3.1.3 on 2022-01-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0012_volumes_nts_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='eia_contents',
            name='nts_link',
            field=models.CharField(default='/none', max_length=250),
        ),
    ]
